### ISSUE TITLE
Convert the RAW BGP data from RIPE

### ISSUE THREAD

**Issue by Ibrahinv** [YoshiyukiYamauchi/mrtparse#29]
Hello , I wish install full routing table in a Router but before Convert the RAW BGP data from RIPE into a format that ExaBGP can process, however i get a issue.

I tried with mrtparse and http://data.ris.ripe.net/rrc16/latest-bview.gz and then with mrt2exabgp -G -P ./latest-bview.gz > fullbgptable.py. The session is UP, not received prefix, but i got the same error message in the router.

sh bgp summary
Neighbor Spk AS MsgRcvd MsgSent TblVer InQ OutQ Up/Down St/PfxRcd
192.168.1.111 0 200 1608 12 4 0 0 00:00:24 0

RP/0/0/CPU0:ios#RP/0/0/CPU0:Oct 21 02:05:15.424 : bgp[1052]: %ROUTING-BGP-3-MALFORM_UPDATE : Malformed UPDATE message received from neighbor 192.168.1.111 (VRF: default) - message length 269 bytes, error flags 0x00000200, action taken "TreatAsWdr". Error details: "Error 0x00000200, Field "Attr-data", Attribute 2 (Flags 0x40, Length 18), Data [40021202040000cc6000000da300000d]". NLRIs: [IPv4 Unicast] 217.14.120.0/22 205.167.22.0/23 205.167.188.0/23 206.221.126.0/23 199.254.216.0/24 200.41.49.0/24 200.41.53.0/24...

The code after mrtparse is:

#!/usr/bin/env python

import sys
import time

msgs = [
'announce attributes origin IGP as-path [199524 2914 ] next-hop 198.32.243.133 nlri 0.0.0.0/0',
'announce attributes origin IGP as-path [199524 2914 ] next-hop 2001:504:0:6:0:19:9524:1 nlri ::/0 2001:218::/32 2001:218:2002::/48 2001:218:8000::/38 2001:418::/32 2001:728::/32 2>
'announce attributes origin IGP as-path [52320 13335 ] med 0 aggregator (13335:108.162.211.10) community [52320:31912] next-hop 198.32.242.254 nlri 1.0.0.0/24 1.1.1.0/24 8.27.64.0/>
'announce attributes origin IGP as-path [6939 4826 38803 ] med 0 next-hop 198.32.242.176 nlri 1.0.4.0/22 1.0.4.0/24 1.0.5.0/24 1.0.6.0/24 1.0.7.0/24 43.252.108.0/22 43.252.108.0/24>
'announce attributes origin IGP as-path [52320 3491 2516 7670 18144 ] med 0 aggregator (18144:219.118.225.18) community [52320:11912] next-hop 198.32.242.254 nlri 1.0.64.0/18 58.18>
'announce attributes origin IGP as-path [6939 38040 23969 ] med 0 next-hop 198.32.242.176 nlri 1.0.128.0/17 1.0.128.0/18 1.0.128.0/19 1.0.130.0/23 1.0.132.0/24 1.0.133.0/24 1.0.136>
'announce attributes origin IGP as-path [6939 4651 23969 ] med 0 next-hop 198.32.242.176 nlri 1.0.128.0/24 1.0.129.0/24 1.0.137.0/24 1.0.144.0/20 1.0.160.0/22 1.0.164.0/24 1.0.165.>
'announce attributes origin IGP as-path [52320 4134 58543 ] med 0 community [52320:21912] next-hop 198.32.242.254 nlri 1.1.8.0/24 121.201.0.0/18 121.201.64.0/18',
.....
while msgs:
    msg = msgs.pop(0)
    if isinstance(msg, str):
        sys.stdout.write(msg + '\n')
        sys.stdout.flush()
    else:
        time.sleep(msg)

while True:
    time.sleep(1)

How can i get data in correct format ?

**Comment by t2mune** [comment]
Hi,

Thank you for using mrtparse !!

There seems to be a problem with AS-Path advertised by ExaBGP.
If you use eBGP, you must include AS 200 in AS-Path as described in RFC4271.
To do so, you need to edit as follows:

    sed -i -e "s/as-path \\[/as-path [200 /" fullbgptable.py

**Comment by t2mune** [comment]
If you can't resolve next-hop advertised, you also need to override next-hop like below:

    mrt2exabgp -G -P -4 192.168.1.111 ./latest-bview.gz > fullbgptable.py.

**Comment by Ibrahinv** [comment]
Yess ¡¡ whith both I can get announce to router and I already got to see the prefixes in the router RIB. However I only receive about 331K prefixes, but then the exaBGP server stops and then the BGP peer goes down.
Is this a bug? How to make to keep it in UP for a longer time?

**Comment by thomas-mangin** [comment]
It is probably due as your session is set up with treat-as-withdraw, so the bad routes will be discarded (instead of tearing the session down). Just guessing.

👋 @t2mune 

was this code written for ExaBGP 3 or 4? - I am asking due to this:
https://github.com/Exa-Networks/exabgp/wiki/Migration-from-3.4-to-4.0

**Comment by t2mune** [comment]
@Ibrahinv 

Can you share the following information? I try to reproduce.

1. ExaBGP version
2. ExaBGP configuration
3. IOS-XR version
4. IOS-XR configuration

**Comment by t2mune** [comment]
@thomas-mangin 

Thank you for your support !!
I didn't care about the difference between versions:cry:, so I'd like to read the document.

**Comment by Ibrahinv** [comment]
I share it. @t2mune 
1.-
home@ubuntu:/opt/exabgp-4.2.6$ exabgp --ver
ExaBGP : 4.2.16
Python : 3.8.10 (default, Sep 28 2021, 16:10:42)  [GCC 9.3.0]
Uname  : Linux ubuntu 5.11.0-38-generic #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021 x86_64
Root   : /home/home/.local
home@ubuntu:/opt/exabgp-4.2.6$ 


------------
2.-ExaBGP configuration

template {
  neighbor cogent {
    local-as 200;
    family {
      ipv4 unicast;
      ipv6 unicast;
    }
  }
}

neighbor 192.168.1.112 {
  inherit cogent;
  router-id 192.168.1.111;
  local-address 192.168.1.111;
  peer-as 22000;
 #graceful-restart;

  auto-flush false;
  group-updates true;
}

process fullbgp {
  #run /usr/bin/python3 /opt/exabgp-4.2.6/fullbgptable.py;
  run /usr/bin/pypy /opt/exabgp-4.2.6/fullbgptable_2.py;
  encoder text;
  
Full BGP table was get it after apply:
mrt2exabgp -G -P -4 192.168.1.111 ./latest-bview.gz > fullbgptable_2.py
sed -i -e "s/as-path \\[/as-path [200 /" fullbgptable_2.py

3.- I tested in IoS-XR version
cisco IOS XRv Series

I tried in Junos too:
Model: vmx
Junos: 21.2R1.10

4.-
RP/0/0/CPU0:ios#sh run router bgp
router bgp 22000
 bgp router-id 100.100.100.1
 address-family ipv4 unicast
 !
 address-family ipv6 unicast
 !
 neighbor 192.168.1.111
  remote-as 200
  address-family ipv4 unicast
   route-policy permit-all in
   route-policy permit-all out

Thanks a lot.

**Comment by t2mune** [comment]
@Ibrahinv 

I was able to reproduce it.
No KEEPALIVE message are sent from ExaBGP, and BGP session is down by sending NOTIFICATION message (Hold Timer Expired) from IOS-XR.
To fix it, environment value `exabgp.api.ack` needs to be `False` when running ExaBGP.

```
env exabgp.api.ack=false exabgp exabgp.conf
```

```
RP/0/0/CPU0:ios#show bgp summary 
Tue Oct 26 19:10:09.459 UTC
BGP router identifier 100.100.100.1, local AS number 22000
BGP generic scan interval 60 secs
Non-stop routing is enabled
BGP table state: Active
Table ID: 0xe0000000   RD version: 6183209
BGP main routing table version 6183209
BGP NSR Initial initsync version 2 (Reached)
BGP NSR/ISSU Sync-Group versions 0/0
BGP scan interval 60 secs

BGP is operating in STANDALONE mode.


Process       RcvTblVer   bRIB/RIB   LabelVer  ImportVer  SendTblVer  StandbyVer
Speaker         6183209    6183209    6183209    6183209     6183209           0

Neighbor        Spk    AS MsgRcvd MsgSent   TblVer  InQ OutQ  Up/Down  St/PfxRcd
192.168.1.111     0   200  414306      96  6183209    0    0 00:28:07     887057

RP/0/0/CPU0:ios#show route summary
Tue Oct 26 19:10:12.389 UTC
Route Source                     Routes     Backup     Deleted     Memory(bytes)
connected                        2          0          0           320          
local                            2          0          0           320          
dagr                             0          0          0           0            
bgp 22000                        887057     0          0           141929120    
Total                            887061     0          0           141929760    

RP/0/0/CPU0:ios#
```

@thomas-mangin 

Thanks again !!

**Comment by Ibrahinv** [comment]
Thank you very much, with this last change the bgp peer remains in UP. Excellent support ¡
