### ISSUE TITLE
Key error when converting MRT to JSON

### ISSUE THREAD

**Issue by ana-gonzalezrios** [YoshiyukiYamauchi/mrtparse#30]

**Comment by ana-gonzalezrios** [comment]
When trying to convert MRT file <updates.20030201.0023.bz2> I get the following error:

[
Traceback (most recent call last):
  File "mrt2json.py", line 16, in <module>
    main()
  File "mrt2json.py", line 8, in main
    for entry in Reader(sys.argv[1]):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mrtparse/__init__.py", line 86, in __next__
    self.unpack_hdr(mrt)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mrtparse/__init__.py", line 116, in unpack_hdr
    mrt.unpack()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mrtparse/__init__.py", line 229, in unpack
    MRT_ST[self.data['type'][0]][self.data['subtype'][0]]
KeyError: 22864

File can be downloaded from:
http://archive.routeviews.org/bgpdata/2003.02/UPDATES/updates.20030201.0023.bz2

**Comment by t2mune** [comment]
Hi,

Thank you for using mrtparse :exclamation:
In my environment, there were no errors.
Could you tell me which version you are using :question: 

```
$ python3 -c "import mrtparse; print(mrtparse.__version__)"
2.1.0
$ mrt2json.py updates.20030201.0023.bz2
[
  {
    "timestamp": {
      "1044087837": "2003-02-01 17:23:57"
    },
    "type": {
      "16": "BGP4MP"
    },
    "subtype": {
      "1": "BGP4MP_MESSAGE"
      (...snip)
      ],
      "nlri": [
        {
          "prefix_length": 24,
          "prefix": "203.196.244.0"
        }
      ]
    }
  }
]

**Comment by ana-gonzalezrios** [comment]
I am running mrtparse 2.0.1 in python 3.10.2 and macOS 12.2.1

**Comment by t2mune** [comment]
I changed the version and tried it, but there was no problem...

```
$ python -c 'import mrtparse; print(mrtparse.__version__)'            
2.0.1
$ ./mrt2json.py updates.20030201.0023.bz2
[
  {
    "timestamp": [
      1044087837,
      "2003-02-01 17:23:57"
    ],
    "type": [
      16,
      "BGP4MP"
    ],
    (...snip)
      ],
      "nlri": [
        {
          "prefix_length": 24,
          "prefix": "203.196.244.0"
        }
      ]
    }
  }
]
```

Your download data might be broken, so could you check the checksum :question: 
In my environment, the checksum is as follows:
```
$ md5sum updates.20030201.0023.bz2                                    
2e15294482ff06f580fc4d6c218a3128  updates.20030201.0023.bz2
```
