### ISSUE TITLE
Error in Example mrt2bgpdump

### ISSUE THREAD

**Issue by GarrettChristian** [YoshiyukiYamauchi/mrtparse#31]
In https://github.com/t2mune/mrtparse/blob/master/examples/mrt2bgpdump.py

I believe there is an issue on line 285:
            seg_t = list(seg['type'])[0]
            for seg in attr['value']:
                if seg_t == AS_PATH_SEG_T['AS_SET']:

I believe it should be
            for seg in attr['value']:
                seg_t = list(seg['type'])[0]
                if seg_t == AS_PATH_SEG_T['AS_SET']:

As in line 242 since seg does not exist prior.

**Comment by t2mune** [comment]
Thank you for letting me know !!
I fixed it.
8e1a68b983343cde950b02399322ea6a65d88cb0
