### ISSUE TITLE
mrt2exabgp mrt2bgpdump key issue for prefix length

### ISSUE THREAD

**Issue by jdhall75** [YoshiyukiYamauchi/mrtparse#32]
I was trying to use mrtparse for exabgp in our lab and found that the prefix length key is set to just `length`, where in the json dump the key is prefix_length.  I  can submit a PR if you like.

(.venv) [jhall@fooji bgp]$ pip list | grep mrt
mrtparse   2.1.0

**Comment by t2mune** [comment]
I recently changed some key names a9081fc304707acf802f56610897e428674ea3ef
So, could you try again using git-clone (v2.2.0.dev0) ?

**Comment by t2mune** [comment]
If you want to install using pip, I will release new version 2.2.0 in PyPI .

**Comment by jdhall75** [comment]
Thanks for the quick response! I made the mrt2exabgp script work with some key changes so I can wait for a release on PyPI and then I'll just upgrade the new release.  Thanks again, - Jason

**Comment by t2mune** [comment]
I've just released new version :smile:
